version: '3'
networks:
    lnmp-local-net:
        driver: bridge
services:
    mysql5.6:
        container_name: mysql5.6
        image: mysql:5.6
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        volumes:
            - $PWD/mysql5.6/db:/var/lib/mysql
            - $PWD/mysql5.6/conf.d:/etc/my.cnf.d
            - $PWD/mysql5.6/logs:/var/log/mysql
            - $PWD/mysql5.6/sql:/data
        restart: always
        networks:
            - lnmp-local-net
    nginx:
        container_name: nginx
        image: nginx:1.19.2
        ports:
            - 80:80
            - 443:443
        volumes:
            - ~/wwwroot:/data/wwwroot
            - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
            - $PWD/nginx/conf.d:/etc/nginx/conf.d
            - $PWD/nginx/logs:/var/log/nginx
        depends_on:
            - mysql5.6
            - redis
            - php7.4
            - php5.6
        restart: always
        networks:
            - lnmp-local-net
    php5.6:
        container_name: php5.6
        image: imoowi/php5.6:v1
        ports:
            - 9001:9000
        volumes:
            - ~/wwwroot:/data/wwwroot
            - $PWD/php5.6/php.ini:/usr/local/etc/php/php.ini
            - $PWD/php5.6/logs:/usr/local/var/log
            - $PWD/php5.6/www.conf:/usr/local/etc/php-fpm.d/www.conf
        restart: always
        networks:
            - lnmp-local-net
    php7.4:
        container_name: php7.4
        build: ./php7.4
        ports:
            - 9000:9000
        volumes:
            - ~/wwwroot:/data/wwwroot
            - $PWD/php7.4/php.ini:/usr/local/etc/php/php.ini
            - $PWD/php7.4/logs:/usr/local/var/log
            - $PWD/php7.4/www.conf:/usr/local/etc/php-fpm.d/www.conf
        depends_on:
            - redis
        restart: always
        networks:
            - lnmp-local-net
    ssdb:
        container_name: ssdb
        image: expert/ssdb
        ports:
            - 8888:8888
        restart: always
        networks:
            - lnmp-local-net
    redis:
        container_name: redis
        image: redis:6.2.1
        ports: 
            - 6379:6379
        volumes:
            - $PWD/redis/db:/data
        restart: always
        networks:
            - lnmp-local-net
    memcache:
        container_name: memcache
        image: memcached:1.5.14
        ports: 
            - 11211:11211
        restart: always
        networks:
            - lnmp-local-net